name: Clang Format Checker
on: [push, pull_request]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: HorstBaerbel/action-clang-format@1.4
        # These are optional (defaults displayed)
        with:
          scandir: '.'
          excludedirs: 'build'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          style: 'file'